### ISSUE TITLE
The entity tree structure is not built correctly

### ISSUE THREAD

**Issue by albertosiena** [RISCOSS/riscoss-corporate#146]
it is possible to have something like in the figure below: c1 has two children: c5 and c2, but in the tree c2 is shown as child of c5
![image 2](https://cloud.githubusercontent.com/assets/10241912/10964452/7f0248e2-83a7-11e5-91bf-4b60d24a9655.png)

**Comment by lidix91** [comment]
This situation can be reproduced doing:
1.       I choose an entity with no children, e.g c3
2.       I define a children, e.g c10
3.       Click save, having c3/c10 in the tree
4.       I define another children, c11
5.       I click save, I have c3/c11,c10 in the tree, the list on the rigth side has other order, c10,c11
6.       I choose the first children on the tree, c11, the element below c3
7.       I create a children, eg. C12
8.       I save
9.       The tree is corrupted: c10 is shown as children od c11 instead of c3. But only the first time that the root (c3) appear in the tree.

Sometimes the tree is not corrupted yet, normally the component with the children appears at the end of children. In that case:
10. Choose the other children, the one without children yet
11. Add a children and save
