### ISSUE TITLE
Relation on an Entity not saved completely (SC-TEI-36)

### ISSUE THREAD

**Issue by teicrb** [RISCOSS/riscoss-corporate#157]
If a parent or children relation is created on an entity these settings are not always saved completely. is Messages regarding operations are shown only for Delete action.

Please refer to Mariella and Arcangelo Antonio for further details

**Comment by lidix91** [comment]
I'm not able to reproduce (0.5.2). We need more detail to identify the cases where the childre-parent relation is not saved completely and what "completely" means.

**Comment by albertosiena** [comment]
This is how to reproduce it:
- select a layer
- create a new contextual info of type "date"
- select an entity of that layer
- set a new child and click "Save"
  nothing happens

**Comment by lidix91** [comment]
I can reproduce the error without modifying anything in the layer.

The problem is that in the Children list appear as a candidate some entities that are not allowed. For example in a hierarchy Product-Project-OSS Component, in a project entity, the list contains Products. If you select a product, the save does not save the relationship.

**Comment by albertosiena** [comment]
But this is a different problem.
if you edit the layer, you can't add even allowed entities.
