### ISSUE TITLE
Delete of an Entity (SC-TEI-17)

### ISSUE THREAD

**Issue by teicrb** [RISCOSS/riscoss-corporate#159]
The Delete of an Entity parent is always possible independently on the Entity children. If an Entity has othere entities associated, it should not be possible to delete it

Please refer to Mariella and Arcangelo Antonio for further details

**Comment by lidix91** [comment]
This is not a bug, it is a new feature.

**Comment by albertosiena** [comment]
Btw, is a feature that needs refinement, because if I have a project that has as child an oss component, I want to be able to delete the project without having to delete the children, and I also may want to remove a child to replace with another one.

**Comment by lidix91** [comment]
Current behaviour is that you remove the parent without removing the children

**Comment by manolodd** [comment]
I think it is necessary to allow removing the parent without need of removing the children. But let the children stay there. Do not remove them.

The contrary should not be possible. Because, otherwise, the project would be incorrectly defined. Not completed.

This behaviour is necessary if you are re-using a given OSS component in more than a single project. You should not be asked to remove the OSS component if you want to remove only ONE OF its parent projects.

**Comment by lidix91** [comment]
An entity cannot be deleted if it has parents
An entity can be deleted if it has children. The children are not deleted
