### ISSUE TITLE
(SC-CEN-14) - Overriding data collected by data collectors is a hell

### ISSUE THREAD

**Issue by manolodd** [RISCOSS/riscoss-corporate#172]
The platform allows overriding raw data collected by any data collector defined in the model. The user has to know the model details in order to know the name of those parameters to be modified. This is not acceptable at this stage. I’ts a root cause of several mistakes. The user is obligated to know any potential parameter of any potential risk model (name, type of data, potential values, format of these values...). The platform should show to the user the fields so that the user is able to fill the needed one without having to know all the parameters.

**Comment by lidix91** [comment]
We need clarification....

If this issue is related to manually adding the data gathered as contextual information, the issue is duplicated (#131)

If the issue is related to modify the input data, the user has the name of the field s/he needs to fill. If the user can change one of the fields means that s/he knows what is this. The risk analysis results shows all the fields involved in the risk session, the user only need this ones (not all the potential for all the risk models).

**Comment by manolodd** [comment]
You're right! I'm closing this one. It is in #131
